name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
          with:
            # Optional. Local and remote branch name where commit is going to be pushed
            #  to. Defaults to the current branch.
            #  You might need to set `create_branch: true` if the branch does not exist.
            branch: publish

            # Optional glob pattern of files which should be added to the commit
            # Defaults to all (.)
            # See the `pathspec`-documentation for git
            # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
            # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
            file_pattern: *.pdf

            # Optional. Options used by `git-push`.
            # See https://git-scm.com/docs/git-push#_options
            push_options: '--force'
            
            # Optional. Create given branch name in local and remote repository.
            create_branch: true
